// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4VTVoRAf9tHU4icZUZOP77oNRMRqWPFw',
    appId: '1:475068962100:web:8b93ae01e437587cb58161',
    messagingSenderId: '475068962100',
    projectId: 'fluttercourse-fed1c',
    authDomain: 'fluttercourse-fed1c.firebaseapp.com',
    storageBucket: 'fluttercourse-fed1c.firebasestorage.app',
    measurementId: 'G-PYR6P7L1Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASbz3rI31oPNVUjBCVnMr1oWTDfMX8a50',
    appId: '1:475068962100:android:6509280302dd20beb58161',
    messagingSenderId: '475068962100',
    projectId: 'fluttercourse-fed1c',
    storageBucket: 'fluttercourse-fed1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiWuXVVC3xvhrUGDFkc8CLXFYMWWlfHPE',
    appId: '1:475068962100:ios:888dab6ac4a47ea5b58161',
    messagingSenderId: '475068962100',
    projectId: 'fluttercourse-fed1c',
    storageBucket: 'fluttercourse-fed1c.firebasestorage.app',
    androidClientId: '475068962100-kbg8q2d1qc0gbk47gdoqsmjv95emnlsn.apps.googleusercontent.com',
    iosClientId: '475068962100-904k6nfsg9iimld01ucr30c7b81p88ks.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiWuXVVC3xvhrUGDFkc8CLXFYMWWlfHPE',
    appId: '1:475068962100:ios:888dab6ac4a47ea5b58161',
    messagingSenderId: '475068962100',
    projectId: 'fluttercourse-fed1c',
    storageBucket: 'fluttercourse-fed1c.firebasestorage.app',
    androidClientId: '475068962100-kbg8q2d1qc0gbk47gdoqsmjv95emnlsn.apps.googleusercontent.com',
    iosClientId: '475068962100-904k6nfsg9iimld01ucr30c7b81p88ks.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4VTVoRAf9tHU4icZUZOP77oNRMRqWPFw',
    appId: '1:475068962100:web:aea507065beff0e6b58161',
    messagingSenderId: '475068962100',
    projectId: 'fluttercourse-fed1c',
    authDomain: 'fluttercourse-fed1c.firebaseapp.com',
    storageBucket: 'fluttercourse-fed1c.firebasestorage.app',
    measurementId: 'G-QSTMKDFB83',
  );

}